[package]
name = "semantic-graph-store"
version.workspace = true
edition.workspace = true

[dependencies]
clap                      = { workspace = true }
error-location            = { workspace = true }
serde_json                = { workspace = true }
sqlx                      = { workspace = true }
thiserror                 = { workspace = true }
tokio                     = { workspace = true }

semantic-graph-config     = { workspace = true }
semantic-graph-db-manager = { workspace = true }

[lints]
workspace                 = true
