[package]
name = "semantic-graph-db-manager"
version.workspace = true
edition.workspace = true

[dependencies]
error-location        = { workspace = true }
hex                   = { workspace = true }
serde_json            = { workspace = true }
sha2                  = { workspace = true }
sqlx                  = { workspace = true }
thiserror             = { workspace = true }
tokio                 = { workspace = true }

semantic-graph-config = { workspace = true }

[lints]
workspace             = true
