[package]
name = "semantic-graph-extract"
version.workspace = true
edition.workspace = true

[dependencies]
clap                      = { workspace = true }
error-location            = { workspace = true }
hex                       = { workspace = true }
lsp-types                 = { workspace = true }
serde_json                = { workspace = true }
sha2                      = { workspace = true }
thiserror                 = { workspace = true }
tokio                     = { workspace = true }

csharp-ls-lib             = { workspace = true }
rust-analyzer-lib         = { workspace = true }
semantic-graph-config     = { workspace = true }
semantic-graph-db-manager = { workspace = true }
semantic-graph-store      = { workspace = true }

[dev-dependencies]
sqlx                      = { workspace = true }

[lints]
workspace                 = true
