[package]
name = "semantic-graph-visualizer-server"
version.workspace = true
edition.workspace = true

[dependencies]
axum           = { workspace = true }
clap           = { workspace = true }
error-location = { workspace = true }
serde          = { workspace = true }
serde_json     = { workspace = true }
sqlx           = { workspace = true }
thiserror      = { workspace = true }
tokio          = { workspace = true }
tower-http     = { workspace = true }

[lints]
workspace = true
