[package]
name = "semantic-graph-query"
version.workspace = true
edition.workspace = true

[dependencies]
error-location            = { workspace = true }
serde                     = { workspace = true }
serde_json                = { workspace = true }
sqlx                      = { workspace = true }
thiserror                 = { workspace = true }

semantic-graph-config     = { workspace = true }

[dev-dependencies]
semantic-graph-db-manager = { workspace = true }
tokio                     = { workspace = true }

[lints]
workspace                 = true
